global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alexey_puzikov'