version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      labs:

  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.6.2
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.6.2
    ports:
      - "5601:5601"
networks:
  labs:
