version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      labs:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      labs:
  post:
    image: ${USERNAME}/post:${POST_VER}
    networks:
      labs:
        aliases:
          - post
  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      labs:
        aliases:
          - comment
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      labs:
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      labs:
  mongo-exporter:
    image: ${USERNAME}/mongodb_exporter
    depends_on:
      - post_db
      - prometheus
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
    networks:
      labs:
  blackbox-exporter:
    image: ${USERNAME}/blackbox_exporter
    depends_on:
      - prometheus
      - ui
      - comment
      - post
    networks:
      labs:
volumes:
  post_db:
  prometheus_data:
networks:
  labs:
