version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      labs:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      labs:
  post:
    image: ${USERNAME}/post:${POST_VER}
    networks:
      labs:
        aliases:
          - post
  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      labs:
        aliases:
          - comment

volumes:
  post_db:
networks:
  labs:
